"""Demo-dog onboarding mode (2026-05-04).

Pairs with `logicd enroll` (production tenant onboarding) but does not
share its code path. The two modes are intentionally separate so that:

  * `enroll` stays the audited, tenant-scoped, keyring-backed path used
    by paying / production users. Nothing in this module touches it.
  * `demo-dog` uses pre-provisioned demo-only credentials for the
    `ghostlogic-demo` tenant. Demo keys are ingester-only on the
    server side and never read capsules. They are easy to rotate
    server-side by editing `/etc/blackbox/keys.json`.

Security envelope (server-side responsibility — see
`docs/DEMO_TENANT_SERVER_SPEC.md` for the operator handoff):

  * Demo key MUST be configured server-side with role=ingester.
  * Demo tenant `ghostlogic-demo` MUST be isolated from real tenants
    (separate row in keys.json, separate capsule storage namespace).
  * The dashboard `/demo` route MUST proxy reads with a scoped
    read-only key; the demo agent's ingester key is NEVER used to
    read.

Workstation-side responsibility (this module):

  * Generate and persist a per-install endpoint_id (UUID4).
  * Write a separate config file (`<root>/agents/logicd-demo.toml`)
    so the demo and production configs never collide.
  * Mark the config `demo_mode = true` so the daemon prints a clear
    "Demo Mode" banner.
  * Print the dashboard URL and the next-step `logicd run` command.
  * Never write the demo key to OS keyring — keep it in the demo
    TOML so rotation is one file edit + restart.
"""
from __future__ import annotations

import argparse
import os
import socket
import sys
import uuid
from pathlib import Path
from textwrap import dedent

from .installer import agent_paths, default_data_dir


# ---------------------------------------------------------------------------
# Demo constants
# ---------------------------------------------------------------------------

DEMO_TENANT = "ghostlogic-demo"
DEMO_AGENT_NAME = "logicd-demo"
DEMO_API_URL = "https://api.ghostlogic.tech"
DEMO_DASHBOARD_URL = "https://blackbox.ghostlogic.tech/demo"

# The pre-provisioned demo key. Two ways to populate it:
#   1. Set GHOSTLOGIC_DEMO_KEY in the environment at install time. The
#      installer (this module) reads it and bakes it into the demo
#      config file. Recommended for a real demo: the build/CI flow
#      sets the env var to the operator-minted demo key.
#   2. Hardcode here at release-time substitution (e.g. via sed in a
#      release script). Leave the placeholder as-is in the repo.
#
# Either way, the operator MUST mint the demo key server-side first
# (see DEMO_TENANT_SERVER_SPEC.md) and ensure it has role=ingester only.
_DEMO_KEY_ENV_VAR = "GHOSTLOGIC_DEMO_KEY"
_DEMO_KEY_PLACEHOLDER = "gl_agent_demo_PLACEHOLDER_REPLACE_BEFORE_RELEASE"


def _resolve_demo_key() -> str:
    """Pull the demo key from env or fall through to the placeholder."""
    return os.environ.get(_DEMO_KEY_ENV_VAR, _DEMO_KEY_PLACEHOLDER)


# ---------------------------------------------------------------------------
# Demo config writer
# ---------------------------------------------------------------------------

def write_demo_config(
    *,
    data_dir: Path,
    api_key: str,
    endpoint_id: str,
    endpoint_name: str,
    api_url: str = DEMO_API_URL,
    dashboard_url: str = DEMO_DASHBOARD_URL,
    tenant: str = DEMO_TENANT,
) -> Path:
    """Write a demo-mode config file under <data_dir>/agents/logicd-demo.toml.

    Distinct from `installer.write_config` and `enroll._write_enrolled_config`
    so the production path is untouched. Keeps the [demo] block + role
    notes that Config.load consumes.
    """
    cfg_path, state_dir, audit_path = agent_paths(data_dir, DEMO_AGENT_NAME)
    for d in (cfg_path.parent, state_dir, audit_path.parent):
        d.mkdir(parents=True, exist_ok=True)

    content = dedent(f"""\
        # GhostLogic Agent Watchdog config — DEMO MODE.
        # Generated by `logicd demo-dog`. Re-run `logicd demo-dog` to
        # rotate or re-provision; or simply delete this file when the
        # demo window ends.
        #
        # The demo key is intentionally NOT in OS keyring: rotation
        # during a demo window should be one file-edit + restart, not
        # a credential-manager dance.

        state_dir = {str(state_dir).replace(chr(92), "/")!r}
        audit_log = {str(audit_path).replace(chr(92), "/")!r}
        heartbeat_seconds = 60

        [api]
        url = "{api_url.rstrip('/')}"
        key = "{api_key}"
        max_concurrent_posts = 1
        endpoint_id = "{endpoint_id}"

        [tick]
        seconds = 600
        window_days = 7

        [privacy]
        # Conservative defaults for demo mode. Even in demo, payloads
        # stay off the wire unless the operator explicitly opts in.
        include_payload = false

        [demo]
        # Load-bearing flag: Config.demo_mode reads this. The daemon
        # prints "Demo Mode" prominently when true.
        mode = true
        tenant = "{tenant}"
        dashboard_url = "{dashboard_url}"
        endpoint_name = "{endpoint_name}"
        # Server-side contract (operator must enforce in keys.json):
        #   - Tenant: {tenant}
        #   - Role:   ingester (no reads)
        #   - Isolated from real tenants
        #
        # Dashboard contract (server-side):
        #   - {dashboard_url} reads only this tenant's data
        #   - Backend proxy or scoped read-only key — NOT this key
    """)

    cfg_path.write_text(content, encoding="utf-8")
    return cfg_path


# ---------------------------------------------------------------------------
# CLI entrypoint
# ---------------------------------------------------------------------------

def run_demo_dog(argv: list[str] | None = None) -> int:
    """`logicd demo-dog` entrypoint. Returns process exit code."""
    parser = argparse.ArgumentParser(
        prog="logicd demo-dog",
        description=(
            "Onboard this host into the GhostLogic demo tenant "
            "(ingester-only, isolated). Uses pre-provisioned demo "
            "credentials. Not for production — see `logicd enroll`."
        ),
    )
    parser.add_argument(
        "--data-dir",
        help="Override the GhostLogic data directory (default: platform-native).",
    )
    parser.add_argument(
        "--endpoint-name",
        help="Override the endpoint label (default: this machine's hostname).",
    )
    parser.add_argument(
        "--api-url",
        default=DEMO_API_URL,
        help=f"Override the demo API URL (default: {DEMO_API_URL}).",
    )
    parser.add_argument(
        "--start",
        action="store_true",
        help="Start the daemon immediately after writing the config.",
    )
    args = parser.parse_args(argv)

    api_key = _resolve_demo_key()
    if api_key == _DEMO_KEY_PLACEHOLDER:
        print(
            "ERROR: demo key not configured.\n"
            f"  Set {_DEMO_KEY_ENV_VAR} in the environment, or replace the\n"
            f"  placeholder in logicd/demo.py at release time. The demo\n"
            f"  key must be minted server-side first with role=ingester\n"
            f"  on tenant {DEMO_TENANT!r}.",
            file=sys.stderr,
        )
        return 2

    data_dir = Path(args.data_dir).expanduser() if args.data_dir else default_data_dir()
    endpoint_name = args.endpoint_name or socket.gethostname()
    endpoint_id = str(uuid.uuid4())

    cfg_path = write_demo_config(
        data_dir=data_dir,
        api_key=api_key,
        endpoint_id=endpoint_id,
        endpoint_name=endpoint_name,
        api_url=args.api_url,
    )

    print()
    print("=" * 60)
    print("  GhostLogic Demo Mode — onboarding complete")
    print("=" * 60)
    print(f"  tenant:       {DEMO_TENANT}")
    print(f"  endpoint:     {endpoint_name}  ({endpoint_id})")
    print(f"  config:       {cfg_path}")
    print(f"  dashboard:    {DEMO_DASHBOARD_URL}")
    print()
    print("  Demo keys are ingester-only. The dashboard reads through")
    print("  a scoped read-only path on the server side; this agent")
    print("  never reads data.")
    print()
    print("  To start the daemon:")
    print(f"    python -m logicd run --config {cfg_path}")
    print()

    if args.start:
        # Lazy import so `demo-dog` doesn't pay the spine/aiohttp boot cost
        # just to write a config.
        from .__main__ import _run as _run_daemon
        return _run_daemon(cfg_path)

    return 0
