"""`logicd enroll --token <token>` — first-run enrollment.

The operator gets an enrollment token from the dashboard
(blackbox.ghostlogic.tech), pastes it into the daemon, and the daemon:

  1. POSTs hostname/platform/os_user + agent_id + requested_event_types
     to /api/v1/agents/enroll on the API server (default
     api.ghostlogic.tech).
  2. Receives a one-time-display scoped `gl_agent_*` key + endpoint_id.
  3. Writes the key into a fresh config.toml under the platform's data
     directory, ACL-locked to owner-only.
  4. Prints the key prefix (not the full key) and instructions to start
     the service.

The full plaintext key is printed exactly once on the first successful
enroll. After this, it lives only in the ACL-locked config and on the
server (hashed). To rotate, mint a new token and re-enroll."""
from __future__ import annotations

import argparse
import getpass
import json
import socket
import sys
import urllib.error
import urllib.request
from pathlib import Path
from textwrap import dedent

from .installer import (
    AGENT_NAME, agent_paths, default_data_dir, lock_acls,
    platform_name, service_instructions,
)


DEFAULT_API_URL = "https://api.ghostlogic.tech"


def _http_post(url: str, body: dict, *, timeout: float = 30.0) -> tuple[int, dict | str]:
    data = json.dumps(body).encode("utf-8")
    req = urllib.request.Request(
        url, data=data, method="POST",
        headers={"Content-Type": "application/json", "Accept": "application/json",
                 "User-Agent": "logicd-enroll/0.1.0"},
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            text = resp.read().decode("utf-8")
            return resp.status, json.loads(text) if text else {}
    except urllib.error.HTTPError as e:
        text = e.read().decode("utf-8") if e.fp else ""
        try:
            return e.code, json.loads(text)
        except (json.JSONDecodeError, ValueError):
            return e.code, text


def _write_enrolled_config(*, data_dir: Path, agent_name: str, api_url: str,
                            api_key: str, endpoint_id: str) -> Path:
    cfg_path, state_dir, audit_path = agent_paths(data_dir, agent_name)
    for d in (cfg_path.parent, state_dir, audit_path.parent):
        d.mkdir(parents=True, exist_ok=True)
    content = dedent(f"""
        # GhostLogic Agent Watchdog config (enrolled).
        # Generated by `logicd enroll`. Re-enroll to rotate the key.

        state_dir = {str(state_dir).replace(chr(92), "/")!r}
        audit_log = {str(audit_path).replace(chr(92), "/")!r}
        heartbeat_seconds = 60

        [api]
        url = "{api_url.rstrip('/')}"
        key = "{api_key}"
        max_concurrent_posts = 3
        endpoint_id = "{endpoint_id}"

        [tick]
        seconds = 600
        window_days = 7

        [privacy]
        # Conservative defaults. Set include_payload=true to ship full
        # transcript bodies (still redacted by the patterns below).
        include_payload = false
        include_default_redactions = true
        # exclude_paths = ["**/secret-project/**"]

        [[watch]]
        name = "claude-code"
        adapter = "claude_code"
        paths = ["~/.claude/projects/*/*.jsonl"]

        [[watch]]
        name = "codex-cli"
        adapter = "codex"
        paths = [
          "~/.codex/sessions/**/*.jsonl",
          "~/.codex/history.jsonl",
        ]
    """).strip() + "\n"
    cfg_path.write_text(content, encoding="utf-8")
    return cfg_path


def run_enroll(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="logicd enroll")
    ap.add_argument("--token", required=True,
                    help="One-shot enrollment token from the dashboard (gl_enroll_...)")
    ap.add_argument("--api-url", default=DEFAULT_API_URL,
                    help=f"Blackbox API base URL (default: {DEFAULT_API_URL})")
    ap.add_argument("--data-dir", help="Override the default data directory")
    ap.add_argument("--endpoint-name",
                    help="Override the endpoint name (default: this machine's hostname)")
    ap.add_argument("--agent-id", default="logicd",
                    help="Agent identifier (default: logicd)")
    ap.add_argument("--no-os-user", action="store_true",
                    help="Don't include the OS user in the enrollment request")
    args = ap.parse_args(argv)

    if not args.token.startswith("gl_enroll_"):
        print("ERROR: token must start with 'gl_enroll_'", file=sys.stderr)
        return 2

    hostname = socket.gethostname()
    plat = platform_name()
    os_user = None if args.no_os_user else getpass.getuser()

    body = {
        "token": args.token,
        "hostname": hostname,
        "platform": plat,
        "os_user": os_user,
        "agent_id": args.agent_id,
        "endpoint_name": args.endpoint_name or hostname,
        "requested_event_types": ["tool_event", "heartbeat"],
    }

    enroll_url = args.api_url.rstrip("/") + "/api/v1/agents/enroll"
    print(f"[enroll] POST {enroll_url}")
    status, resp = _http_post(enroll_url, body)

    if status != 201:
        detail = resp.get("detail") if isinstance(resp, dict) else resp
        print(f"ERROR: enroll failed (HTTP {status}): {detail}", file=sys.stderr)
        return 3

    plaintext = resp["plaintext_key"]
    key_prefix = resp["key_prefix"]
    endpoint_id = resp["endpoint_id"]
    server_api_url = resp.get("api_url") or args.api_url

    data_dir = Path(args.data_dir).expanduser() if args.data_dir else default_data_dir()
    cfg_path = _write_enrolled_config(
        data_dir=data_dir, agent_name=AGENT_NAME, api_url=server_api_url,
        api_key=plaintext, endpoint_id=endpoint_id,
    )
    ok, acl_desc = lock_acls(cfg_path)

    print()
    print("-- enrollment success --")
    print(f"  endpoint:  {resp['endpoint_name']}  ({endpoint_id})")
    print(f"  agent_id:  {resp['agent_id']}")
    print(f"  key:       {key_prefix}...   (full key shown once below)")
    print(f"  types:     {', '.join(resp['allowed_event_types'])}")
    print(f"  config:    {cfg_path}")
    print(f"  acl lock:  {acl_desc}" + ("" if ok else "  (WARNING: not locked)"))
    print()
    print("Full agent key (DO NOT show again -- rotate by re-enrolling):")
    print(f"  {plaintext}")
    print()
    print(service_instructions(sys.executable, cfg_path))
    print()
    return 0
